### PR TITLE
feat: update footer icons

### PR DESCRIPTION
**Pull request by mikepawlinski**
Slightly improves web vitals

|before|after|
|---|---|
| Screenshot 2023-01-23 at 13 32 02 Screenshot 2023-01-23 at 13 32 12 | Screenshot 2023-01-23 at 13 32 19 Screenshot 2023-01-23 at 13 32 29 |

### CODE REVIEW

**Review by alvarocavalcanti — DISMISSED** [review]
LGTM

**Review by RossoMaguire — CHANGES_REQUESTED** [review]
Kind of pedantic but the BC logo doesn't seem as centered on Desktop as before. It seems to be starting a little more outside the footer nav than previously. Could we use Flexbox or grid to center / justify them evenly ?

**Comment by mikepawlinski** [comment]
@RossoMaguire yes I see it now (focused way too more on mobile I guess), let me fix that

**Comment by mikepawlinski** [comment]
Screenshot 2023-01-23 at 13 53 55

**Review by alvarocavalcanti — APPROVED** [review]

**Review by RossoMaguire — APPROVED** [review]
Nice one!

**Pull request merged**
